### ISSUE TITLE
Memory leak in jk_cachedObjects

### ISSUE THREAD

**Issue by mast** [johnezang/JSONKit#53] opened 2011-10-20 16:49 UTC
I observe memory leaks, which may be quite significant for me.

I do the following code in my view controller:

```
JSONDecoder *json = [JSONDecoder decoder];

if (![data isKindOfClass:[NSData class]])
{
    // Error occurred
    return;
}

// Ok, data is received, parse it
NSDictionary *parsed = [json objectWithData:data];
```

As soon as I move to another controller I get:

Leaked Object   #   Address Size    Responsible Library Responsible Frame
NSCFString,5    < multiple >    144 Bytes   App jk_cachedObjects
 NSCFString,1   0x18ac40    32 Bytes     App    jk_cachedObjects
 NSCFString,1   0x18b340    16 Bytes    App jk_cachedObjects
 NSCFString,1   0x18b7e0    32 Bytes     App    jk_cachedObjects
 NSCFString,1   0x18bc90    32 Bytes    App jk_cachedObjects
 NSCFString,1   0x18cb60    32 Bytes     App    jk_cachedObjects

id  Address Category    Event Type  RefCt   Timestamp   Size    Responsible Library Responsible Caller
0   0x18ac40    CFString (immutable)    Malloc  1   00:15.891.265   32  App jk_cachedObjects
1   0x18ac40    CFString (immutable)    CFRetain    2   00:15.891.302   0   App jk_cachedObjects
2   0x18ac40    CFString (immutable)    CFRetain    3   00:15.903.345   0   Foundation  -[NSCFString retain]
3   0x18ac40    CFString (immutable)    CFRelease   2   00:15.973.275   0   App -[JKDictionary dealloc]
4   0x18ac40    CFString (immutable)    CFRelease   1   00:15.980.459   0   App -[JSONDecoder clearCache]

I shouldn't do the following, is it? At least it's not obvious that I should.

   [json release];
   [parsed release];

I parse lots of data (at least once each 5 minutes), so such leak is quite critical for me.
Can you be so kind as to dig into this? May be it's just my stupid fault, but it doesn't look like that for me right now.

**Comment by johnezang** [comment] 2011-10-21 18:52
While there certainly exists the possibility that there is a memory leak inside JSONKit, at this point it has been in heavy use by a very large number of projects at this point, and most of the major bugs have been fixed.

Pragmatically, this means that the most likely cause of the memory leak is a bug in your code, not JSONKit.  The leak information you're getting is the stack trace of where the allocation took place, which is not the same thing as where that allocation was leaked.

The most likely explanation is that you have over retained something that JSONKit has given you.  Unfortunately, it is simply not possible for me to offer any more assistance than this generic advice.  For now, I'm going to close this bug, but if you have additional information which clearly implicates JSONKit, feel free to re-open this bug or open a new one.

**Closed as completed by johnezang** 2011-10-21 18:52 UTC
Labels: Unable To Reproduce, May Be Bug or Possibly User Error

**Comment by mast** [comment] 2011-10-24 18:15
Thanks for your response. You was right and I found leak in my code in very non-obvious place. Sorry that I was complaining JSONKit!

**Comment by jkubicek** [comment] 2012-03-22 17:58
I'm seeing the same leak. See this line of code in jk_cachedObjects:

https://github.com/johnezang/JSONKit/blob/master/JSONKit.m#L2038

```
switch(parseState->token.value.type) {
    case JKValueTypeString:           parsedAtom = (void *)CFStringCreateWithBytes(NULL, parseState->token.value.ptrRange.ptr, parseState->token.value.ptrRange.length, kCFStringEncodingUTF8, 0); break;
    case JKValueTypeLongLong:         parsedAtom = (void *)CFNumberCreate(NULL, kCFNumberLongLongType, &parseState->token.value.number.longLongValue);                                             break;
    case JKValueTypeUnsignedLongLong:
      if(parseState->token.value.number.unsignedLongLongValue <= LLONG_MAX) { parsedAtom = (void *)CFNumberCreate(NULL, kCFNumberLongLongType, &parseState->token.value.number.unsignedLongLongValue); }
      else { parsedAtom = (void *)parseState->objCImpCache.NSNumberInitWithUnsignedLongLong(parseState->objCImpCache.NSNumberAlloc(parseState->objCImpCache.NSNumberClass, @selector(alloc)), @selector(initWithUnsignedLongLong:), parseState->token.value.number.unsignedLongLongValue); }
      break;
    case JKValueTypeDouble:           parsedAtom = (void *)CFNumberCreate(NULL, kCFNumberDoubleType,   &parseState->token.value.number.doubleValue);                                               break;
    default: jk_error(parseState, @"Internal error: Unknown token value type. %@ line #%ld", [NSString stringWithUTF8String:__FILE__], (long)__LINE__); break;
  }

  if(JK_EXPECT_T(setBucket) && (JK_EXPECT_T(parsedAtom != NULL))) {
    bucket = useableBucket;
    if(JK_EXPECT_T((parseState->cache.items[bucket].object != NULL))) { CFRelease(parseState->cache.items[bucket].object); parseState->cache.items[bucket].object = NULL; }

    if(JK_EXPECT_T((parseState->cache.items[bucket].bytes = (unsigned char *)reallocf(parseState->cache.items[bucket].bytes, parseState->token.value.ptrRange.length)) != NULL)) {
      memcpy(parseState->cache.items[bucket].bytes, parseState->token.value.ptrRange.ptr, parseState->token.value.ptrRange.length);
      parseState->cache.items[bucket].object = (void *)CFRetain(parsedAtom);
      parseState->cache.items[bucket].hash   = parseState->token.value.hash;
      parseState->cache.items[bucket].cfHash = 0UL;
      parseState->cache.items[bucket].size   = parseState->token.value.ptrRange.length;
      parseState->cache.items[bucket].type   = parseState->token.value.type;
      parseState->token.value.cacheItem      = &parseState->cache.items[bucket];
      parseState->cache.age[bucket]          = JK_INIT_CACHE_AGE;
    } else { // The realloc failed, so clear the appropriate fields.
      parseState->cache.items[bucket].hash   = 0UL;
      parseState->cache.items[bucket].cfHash = 0UL;
      parseState->cache.items[bucket].size   = 0UL;
      parseState->cache.items[bucket].type   = 0UL;
    }
  }

  return(parsedAtom);
```

`parsedAtom` is created with a `create` method, yielding an object with +1 retain count. `CFRetain` is called on the parsedAtom yeilding a +2 retain count. The parsedAtom is not released.

Just making the change to remove the `CFRetain` isn't sufficient; the parsedAtom is used elsewhere as a key in a `JKObjectStack`, but not retained when it's added to that stack. I'm not sure what the proper solution is here, but I'm looking into it.

**Comment by johnezang** [comment] 2012-03-22 18:25
@jkubicek,

Please open a ticket with a concise test case that reproduces the memory leak.

At this point JSONKit is fairly mature and stable, and used in a lot of real world applications, none of which are experiencing memory leaks due to JSONKit.

To the best of my knowledge, every report of JSONKit leaking memory has turned out to be user error- the leak was caused by over retaining an object that was created by JSONKit.  The memory leak tools can only show you the call stack that allocated the memory that was (eventually) leaked, NOT where the leak took place.
