### ISSUE TITLE
Cannot serialize integers in Mac OS X 10.7

### ISSUE THREAD

**Issue by andypotion** [johnezang/JSONKit#15] opened 2011-04-08 23:00 UTC
The following code will crash in Mac OS X Lion Developer Preview 2:

[[NSArray arrayWithObject:[NSNumber numberWithInteger:1]] JSONString]

The crash happens when you try to get the isa value for the number object because they seem to be optimized special pointers in the runtime now.

**Comment by johnezang** [comment] 2011-04-11 00:27
After working with Andy on this bug (thanks @andypotion!), we were able to determine the cause of the problem.

However, since this is a bug that is specific to Mac OS X 10.7 / Lion, there are various NDA issues involved in discussing the problem publicly.

A work-around is known, but there's a legitimate question as to whether or not this is a bug in JSONKit or not.  It's not clear if the work around should be checked in or if the problem should be resolved "up stream" from JSONKit, so to speak.

**Comment by johnezang** [comment] 2011-04-11 00:33
This is likely a duplicate of issue #9.

**Comment by snej** [comment] 2011-07-17 04:33
JSONKit is groping into an NSNumber object to dereference the 'isa' field. As far as I know this is not kosher since it makes assumptions about object memory layout that Apple could change in future OS versions, including Lion. I don't think you can assign blame upstream to Foundation.

This is probably faster than using the Obj-C runtime API to look up the class, but I don't think you can continue to do it, at least not in these hypothetical future OS versions/configurations where Apple may or may not have changed the layout of certain objects. You might need to use #ifdefs to fall back to safer, if slower, techniques.

**Comment by snej** [comment] 2011-07-22 00:43
Now that Lion is no longer under NDA, could someone please post the workaround as a patch?

**Comment by hiltonc** [comment] 2011-07-22 22:36
I'm also running into this problem. Anyone have a fix?

**Comment by snej** [comment] 2011-07-22 22:39
My current workaround is to use NSJSONSerialization instead, when it's available. I do a runtime check to look up the class by name, and then call it if it's there instead of JSONKit.

**Comment by 0xced** [comment] 2011-07-23 07:26
I guess that [Tagged pointers and fast-pathed CFNumber integers in Lion](http://objectivistc.tumblr.com/post/7872364181) is the cause of this problem.

**Comment by andypotion** [comment] 2011-07-23 19:23
I just submitted a pull request for this. People needing the fix ASAP should check out my fork.

**Comment by johnezang** [comment] 2011-09-23 23:41
Fixed in commit johnezang/JSONKit@c2ef69242b60dc2475328b08131f9aa3078a51fb.

**Closed as completed** 2011-09-23 23:41 UTC
Labels: Crashing, Fixed, Workaround Known, May Be Duplicate
