### ISSUE TITLE
Type mismatch

### ISSUE THREAD

**Issue by soffes** [johnezang/JSONKit#6] opened 2011-03-03 21:45 UTC
There is a warning converting CFHashCode to NSUInteger. I tried typecasting, but this craziness is out of my league :)

http://soff.me/4zWE

I'm using LLVM 2 by the way.

**Comment by johnezang** [comment] 2011-03-03 22:03
I don't have LLVM 2 (the shipping version, at least), but I do have a fairly recent SVN version that I use to test: `clang version 2.0 (trunk 106308)`.  I couldn't reproduce this exact problem with (choice of compiler warning flags?), but none the less I added a type cast.  The fix, along with some other changes, was checked in.

**Comment by soffes** [comment] 2011-03-03 22:43
Fixed my issues. Thanks! Ya, I have stricter warnings on.

**Closed as completed** 2011-03-04 06:03 UTC
Labels: Cosmetic, Fixed
