### ISSUE TITLE
_JKDictionaryHashTableEntryForKey crashes for NULL capacity

### ISSUE THREAD

**Issue by jkustan** [johnezang/JSONKit#38] opened 2011-07-12 18:24 UTC
I have had great success using JSONKit -- however today I was getting a crash in _JKDictionaryHashTableEntryForKey.  As I dug in, it seems that dictionary->capacity was NULL, and the code was dying here:

  NSUInteger        keyHash = CFHash(aKey), keyEntry = (keyHash % dictionary->capacity), idx = 0UL;

I added a NULL check immediately above:

  if(!dictionary->capacity) { return(NULL); }

and now things seem to be going through.

Jack

**Comment by omarkilani** [comment] 2011-07-13 06:12
I think this issue is a duplicate of #31 and was fixed in 18a0a3a.

Are you using the latest git version?

**Comment by jkustan** [comment] 2011-07-13 15:09
I was using a 1.3 download, just moved up to 1.4, and manually added that
patch.  Do you have a recommendation on using the latest vs. using the 1.4
download?

Thanks for putting this together!

Jack

**Comment by johnezang** [comment] 2011-08-19 17:06
As noted by @omarkilani, this is a known bug.

My personal recommendation is to use the latest from `master` (at least as of this date, which would be johnezang/JSONKit@c2146ffeb10d92bfa1537d2033a3235825d1b261).

I should probably create a `stable` branch as well that has all the patches since the last release.. hmmm.

**Closed as completed by johnezang** 2011-08-19 17:06 UTC
Labels: Bug, Crashing, Duplicate, Fixed
